---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Tests
description: Takes an app, app image and token then runs app tests

inputs:
  app:
    description: App Name
    required: true
  image:
    description: Image
    required: true
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Mise
      uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      with:
        experimental: true
        install_args: --locked

    - name: Restore Go Modules
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

    - name: Run Tests
      shell: bash
      env:
        APP: ${{ inputs.app }}
        TEST_IMAGE: ${{ inputs.image }}
      run: |-
        go test -v ./apps/${APP}/...
