---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Tests
description: Takes an app, app image and token then runs app tests

inputs:
  app:
    description: App Name
    required: true
  image:
    description: Image
    required: true
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Mise
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        experimental: true
        install_args: --locked

    - name: Restore Go Modules
      uses: actions/cache/restore@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

    - name: Run Tests
      shell: bash
      env:
        APP: ${{ inputs.app }}
        TEST_IMAGE: ${{ inputs.image }}
      run: |-
        go test -v ./apps/${APP}/...
