[pre-commit]
parallel = true

[pre-commit.commands.format-go]
run = "gofmt -s -w {staged_files}"
glob = ["*.go"]
stage_fixed = true

[pre-commit.commands.format-just]
run = """
for file in {staged_files}; do
    just --justfile "$file" --fmt --unstable
done
"""
glob = ["*.just", ".justfile"]
stage_fixed = true

[pre-commit.commands.format-yaml]
run = "yamlfmt {staged_files}"
glob = ["*.yaml"]
stage_fixed = true
