---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  merge_group:
  pull_request:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get changed files
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        id: changed-files
        with:
          path: apps
          include_only_directories: true
          max_depth: 1

  build:
    if: ${{ needs.prepare.outputs.changed-files != '[]' }}
    name: Build ${{ matrix.app }}
    needs:
      - prepare
    uses: ./.github/workflows/app-builder.yaml
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    secrets:
      BOT_CLIENT_ID: ${{ secrets.BOT_CLIENT_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.changed-files) }}
      fail-fast: false
      max-parallel: 4
    with:
      app: ${{ matrix.app }}
      release: false

  status:
    if: ${{ !cancelled() }}
    name: Build Success
    needs:
      - build
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: |-
          echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
